with open("exception.py","r") as f:
    x = f.read()

print(x)